---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/21/2020 4:42 PM
---
require ("__erm_toss_economy__/prototypes/circuit_connector_definitions")
local ERM_UnitTint = require("__enemyracemanager__/lib/rig/unit_tint")
local TossSound = require("__erm_toss_hd_assets__/sound")
local AnimationDB = require("__erm_toss_hd_assets__/animation_db")
local util = require("util")
local hit_effects = require ("__base__/prototypes/entity/hit-effects")
local sounds = require ("__base__/prototypes/entity/sounds")

local name = "nexus"

local collision_box = { { -4, -4 }, { 4, 4 } }
local map_generator_bounding_box = { { -5, -5 }, { 5, 5 } }
local selection_box = { { -4, -4 }, { 4, 4 } }

local Unit = {}

function Unit.make(prefix)
    local idle = AnimationDB.get_layered_animations("buildings", name, "run")

    idle = AnimationDB.change_frame_count(idle, 1)

    idle = AnimationDB.alter_team_color(idle, nil, true)

    local working = AnimationDB.get_layered_animations("buildings", name, "run")

    working = AnimationDB.alter_team_color(working, nil, true)

    data:extend({
        {
            type = "assembling-machine",
            name = prefix .. "--controllable--"..name,
            icons = {
                {
                    icon = "__erm_toss_hd_assets__/graphics/entity/icons/buildings/advisor.png",
                    icon_size = 64,
                },
            },
            flags = {"placeable-neutral","placeable-player", "player-creation"},
            minable = {mining_time = 1, result = prefix .. "--controllable--"..name},
            max_health = 2500,
            corpse = "protoss--large-base-corpse",
            dying_explosion = "protoss--large-building-explosion",
            allow_run_time_change_of_is_military_target = false,
            is_military_target = true,
            circuit_wire_max_distance = erm_toss_economy_circuit_wire_max_distance,
            circuit_connector = erm_toss_economy_connector['nexus'],
            is_military_target = true,
            resistances =
            {
                { type = "poison", percent = 50 },
                { type = "physical", percent = 50 },
                { type = "fire", percent = 50 },
                { type = "explosion", percent = 50},
                { type = "laser", percent = 50 },
                { type = "electric", percent = 50 },
                { type = "cold", percent = 50},
                { type = "impact", percent = 90, decrease = 50 },
            },
            collision_box = collision_box,
            selection_box = selection_box,
            map_generator_bounding_box = map_generator_bounding_box,
            damaged_trigger_effect = hit_effects.entity(),
            energy_source =
            {
                type = "electric",
                usage_priority = "secondary-input",
                emissions_per_minute = { pollution = 5 }
            },
            energy_usage = "1MW",
            crafting_categories = {prefix.."--erm_controllable"},
            crafting_speed = 1,
            graphics_set = {
                animation = working,
                idle_animation = idle,
            },
            open_sound = sounds.machine_open,
            close_sound = sounds.machine_close,
            vehicle_impact_sound = sounds.generic_impact,
            working_sound = TossSound.building_working_sound("nexus", 0.9),
            dying_sound = TossSound.building_dying_sound(0.9),
            map_color = ERM_UnitTint.tint_army_color(),
            enemy_map_color = { r=1, b=0, g=0 },
        },
    })
end
return Unit