---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/25/2025 1:31 PM
---
--- Create zerg playable units
---
local ProtossPlayableEntity = {}

local zealot = require('prototypes/entities/zealot')
local dragoon = require('prototypes/entities/dragoon')
local corsair = require('prototypes/entities/corsair')
local arbiter = require('prototypes/entities/arbiter')
local darktemplar = require('prototypes/entities/darktemplar')
local archon = require('prototypes/entities/archon')
local nexus = require('prototypes/entities/nexus')

function ProtossPlayableEntity.zealot(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    zealot.make(prefix, hp_mp, damage_mp)
end

function ProtossPlayableEntity.dragoon(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    dragoon.make(prefix, hp_mp, damage_mp)
end

function ProtossPlayableEntity.corsair(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    corsair.make(prefix, hp_mp, damage_mp)
end

function ProtossPlayableEntity.arbiter(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    arbiter.make(prefix, hp_mp, damage_mp)
end

function ProtossPlayableEntity.darktemplar(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    darktemplar.make(prefix, hp_mp, damage_mp)
end

function ProtossPlayableEntity.archon(prefix, hp_mp, damage_mp)
    hp_mp = hp_mp or 1
    damage_mp = damage_mp or 1
    archon.make(prefix, hp_mp, damage_mp)
end

function ProtossPlayableEntity.nexus(prefix)
    nexus.make(prefix)
end

function ProtossPlayableEntity.init(prefix)
    data:extend({
        { 
            type = "recipe-category", 
            name = prefix.."--erm_controllable" 
        },
        {
            type = "item-subgroup",
            name = prefix.."--erm_controllable" ,
            group = "army",
            order = prefix.."--erm_controllable"
        },
        {
            type = "ammo-category",
            name = prefix.."--erm_controllable",
            icon = "__erm_toss_hd_assets__/graphics/entity/icons/buildings/advisor.png",
            subgroup = "ammo-category"
        },
    })
end

return ProtossPlayableEntity