---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/25/2025 1:31 PM
---
--- Create protoss recipe and items
---
local ArmyEconomyHelper = require('__erm_libs__/prototypes/army_economy_helper')
local ProtossItemRecipe = {}

function ProtossItemRecipe.zealot(prefix, ingredients)
    ArmyEconomyHelper.create_item({
        prefix = prefix,
        name = 'zealot',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/zealot.png",
        subgroup = prefix.."--erm_controllable",
        stack_size = 20,
        weight = 50,
    })

    ArmyEconomyHelper.create_recipe({
        prefix = prefix,
        name = 'zealot',
        energy_required = 24,
        ingredients = ingredients,
        category = prefix.."--erm_controllable",
        amount = 1
    })

    ArmyEconomyHelper.create_deploy_recipe({
        prefix = prefix,
        name = 'zealot',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/zealot.png",
        category = prefix.."--erm_controllable",
    })
end

function ProtossItemRecipe.dragoon(prefix, ingredients)
    ArmyEconomyHelper.create_item({
        prefix = prefix,
        name = 'dragoon',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/dragoon.png",
        subgroup = prefix.."--erm_controllable",
        stack_size = 20,
        weight = 100,
    })

    ArmyEconomyHelper.create_recipe({
        prefix = prefix,
        name = 'dragoon',
        energy_required = 25,
        ingredients = ingredients,
        category = prefix.."--erm_controllable",
        amount = 1
    })

    ArmyEconomyHelper.create_deploy_recipe({
        prefix = prefix,
        name = 'dragoon',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/dragoon.png",
        category = prefix.."--erm_controllable",
    })
end

function ProtossItemRecipe.corsair(prefix, ingredients)
    ArmyEconomyHelper.create_item({
        prefix = prefix,
        name = 'corsair',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/corsair.png",
        subgroup = prefix.."--erm_controllable",
        stack_size = 20,
        weight = 100,
    })

    ArmyEconomyHelper.create_recipe({
        prefix = prefix,
        name = 'corsair',
        energy_required = 30,
        ingredients = ingredients,
        category = prefix.."--erm_controllable",
        amount = 1
    })

    ArmyEconomyHelper.create_deploy_recipe({
        prefix = prefix,
        name = 'corsair',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/corsair.png",
        category = prefix.."--erm_controllable",
    })
end

function ProtossItemRecipe.arbiter(prefix, ingredients)
    ArmyEconomyHelper.create_item({
        prefix = prefix,
        name = 'arbiter',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/arbiter.png",
        subgroup = prefix.."--erm_controllable",
        stack_size = 10,
        weight = 200,
    })

    ArmyEconomyHelper.create_recipe({
        prefix = prefix,
        name = 'arbiter',
        energy_required = 60,
        ingredients = ingredients,
        category = prefix.."--erm_controllable",
        amount = 1
    })

    ArmyEconomyHelper.create_deploy_recipe({
        prefix = prefix,
        name = 'arbiter',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/arbiter.png",
        category = prefix.."--erm_controllable",
    })
end

function ProtossItemRecipe.darktemplar(prefix, ingredients)
    ArmyEconomyHelper.create_item({
        prefix = prefix,
        name = 'darktemplar',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/darktemplar.png",
        subgroup = prefix.."--erm_controllable",
        stack_size = 20,
        weight = 500,
    })

    ArmyEconomyHelper.create_recipe({
        prefix = prefix,
        name = 'darktemplar',
        energy_required = 30,
        ingredients = ingredients,
        category = prefix.."--erm_controllable",
        amount = 1
    })

    ArmyEconomyHelper.create_deploy_recipe({
        prefix = prefix,
        name = 'darktemplar',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/darktemplar.png",
        category = prefix.."--erm_controllable",
    })
end

function ProtossItemRecipe.archon(prefix, ingredients)
    ArmyEconomyHelper.create_item({
        prefix = prefix,
        name = 'archon',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/archon.png",
        subgroup = prefix.."--erm_controllable",
        stack_size = 10,
        weight = 500,
    })

    ArmyEconomyHelper.create_recipe({
        prefix = prefix,
        name = 'archon',
        energy_required = 60,
        ingredients = ingredients,
        category = prefix.."--erm_controllable",
        amount = 1
    })

    ArmyEconomyHelper.create_deploy_recipe({
        prefix = prefix,
        name = 'archon',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/units/archon.png",
        category = prefix.."--erm_controllable",
    })
end

function ProtossItemRecipe.nexus(prefix, ingredients)
    ArmyEconomyHelper.create_item({
        prefix = prefix,
        name = 'nexus',
        icon = "__erm_toss_hd_assets__/graphics/entity/icons/buildings/advisor.png",
        subgroup = "erm_controllable_buildings",
        stack_size = 5,
        weight = 10000,
    })

    ArmyEconomyHelper.create_recipe({
        prefix = prefix,
        name = 'nexus',
        energy_required = 60,
        ingredients = ingredients,
        category = "crafting",
        amount = 1
    })
end

function ProtossItemRecipe.technologies(prefix)
    data:extend({
        {
            type = "technology",
            name = prefix .. "--controllable-unlock",
            order = prefix .. "--controllable-unlock",
            icon_size = 64,
            icon = "__erm_toss_hd_assets__/graphics/entity/icons/buildings/advisor.png",
            effects =
            {
                {
                    type = "unlock-recipe",
                    recipe = prefix .. "--controllable--nexus"
                },
                {
                    type = "unlock-recipe",
                    recipe = prefix .. "--controllable--zealot"
                },
                {
                    type = "unlock-recipe",
                    recipe = prefix .. "--controllable--dragoon"
                },
                {
                    type = "unlock-recipe",
                    recipe = prefix .. "--controllable--corsair"
                },
                {
                    type = "unlock-recipe",
                    recipe = prefix .. "--controllable--arbiter"
                },
                {
                    type = "unlock-recipe",
                    recipe = prefix .. "--controllable--darktemplar"
                },
                {
                    type = "unlock-recipe",
                    recipe = prefix .. "--controllable--archon"
                },
            },
            prerequisites = {"military-4","military-science-pack"},
            unit =
            {
                ingredients =
                {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"military-science-pack", 1},
                    {"utility-science-pack", 1},
                    {"space-science-pack", 1},
                    {"metallurgic-science-pack", 1},
                    {"agricultural-science-pack", 1},
                    {"electromagnetic-science-pack", 1},
                    {"cryogenic-science-pack", 1},
                },
                time = 60,
                count = 1000
            },
        },
        {
            type = "technology",
            name = prefix .. "--controllable-damage",
            order = prefix .. "--controllable-damage",
            icon_size = 64,
            icon = "__erm_toss_hd_assets__/graphics/entity/icons/buildings/advisor.png",
            effects =
            {
                {
                    type = "ammo-damage",
                    ammo_category = prefix.."--erm_controllable",
                    modifier = 0.2
                }
            },
            prerequisites = {prefix .. "--controllable-unlock"},
            unit =
            {
                count_formula = "2^(L)*5000",
                ingredients =
                {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"military-science-pack", 1},
                    {"utility-science-pack", 1},
                    {"space-science-pack", 1},
                    {"metallurgic-science-pack", 1},
                    {"agricultural-science-pack", 1},
                    {"electromagnetic-science-pack", 1},
                    {"cryogenic-science-pack", 1},
                    {"promethium-science-pack", 1}
                },
                time = 60,
            },
            max_level = 10,
            upgrade = true
        },
    })
end

return ProtossItemRecipe